#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.expand_path('../lib', __dir__)

require 'active_support/notifications'
require 'active_support/log_subscriber'
require 'logger'
require 'concurrent'
require 'profile-tools'
require 'irb'

ActiveSupport::LogSubscriber.logger = Logger.new($stdout)
ProfileTools::AggregateLogSubscriber.attach_to :profile_tools

IRB.start(__FILE__)
